<?xml version="1.0"?>
<robot name="rotary_inverted_pendulum" xmlns:xacro="http://www.ros.org/wiki/xacro">


    <xacro:property name = "base_height" value="0.3" />
    <xacro:property name = "arm_length" value="0.06 " />
    <xacro:property name = "pendulum_length" value="0.2 " />

    <material name="grey">
        <color rgba="0.7 0.7 0.7 1"/>
    </material>

    <material name="green">
        <color rgba="0 0.6 0 1"/>
    </material>

    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>

    <link name="base_link">
        <visual>
            <geometry>
                <cylinder radius="0.05" length="${base_height}"/>
            </geometry>
            <origin xyz="0 0 ${base_height / 2}" rpy="0 0 0"/>
            <material name="green"/>
        </visual>
    </link>

    <link name="arm_link">
        <visual>
            <geometry>
                <box size="${arm_length} 0.03 0.01"/>
            </geometry>
            <origin xyz="${arm_length / 2} 0 0" rpy="0 0 0"/>
            <material name="grey"/>
        </visual>
    </link>

    <link name="pendulum_link">
        <visual>
            <geometry>
                <box size="${pendulum_length} 0.03 0.01"/>
            </geometry>
            <origin xyz="${pendulum_length / 2}  0 0" rpy="0 0 0"/>
            <material name="red"/>
        </visual>
    </link>

    <joint name="base_arm_joint" type="revolute">
        <parent link="base_link"/>
        <child link="arm_link"/>
        <origin xyz="0 0 ${base_height}" rpy="0 0 0"/>
        <axis xyz="0 0 1"/> 
        <limit effort="10" lower="-${pi}" upper="${pi}" velocity="1.0"/>
    </joint>  

    <joint name="arm_pendulum_joint" type="revolute">
        <parent link="arm_link"/> 
        <child link="pendulum_link"/>
        <origin xyz="${arm_length} 0 0" rpy="0 ${pi / 2.0} 0"/> 
        <axis xyz="0 0 1"/> 
        <limit effort="10" lower="-${pi}" upper="${pi}" velocity="1.0"/>
    </joint>
</robot>
